spring:
  application:
    name: NeonAi

  datasource:
    url: jdbc:postgresql://localhost:5432/lovableDB
    username: postgres
    password: 960494
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

stripe:
  api:
    secret: sk_test_51SthHsJGEVWtB7VxwH6hZZJf5ty2TEURnFSqMarRe2l9gGvXOQdzgxt3tK8cLwwDkPmrdvFxEHHnfZYXAIsyDg7T007zhhs1r7
  webhook:
    secret: whsec_ad27b04ed240526a459e0a63865a51e46c4e895682651d12bd7b9c69389a9fc2

client:
  url: http://localhost:8080